import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';

export const metadata: Metadata = {
  title: 'Sport | Profile',
  description: 'Generated by create next app',
};

export default function Layout({ children }: PropsWithChildren) {
  return <div className='mt-5 px-5 min-h-screen flex justify-center'>{children}</div>;
}
